name: ACR Sysdig Secure Inline Scan

on:
  push:
    branches:
      - main

jobs:
  sysdig-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ACR login
        run: az acr login -n sdtestacr -u sdtestacr -p HZxZuXhGAG+AxAuWHKgczl2agtwNg2oOOdEN+sy4W7+ACRBdYroG

      - name: Sysdig Secure Inline Scan
        uses: sysdiglabs/scan-action@v3
        with:
          image-tag: ${{ secrets.ACR_IMAGE_NAME }}
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          sysdig-monitor-token: ${{ secrets.SYSDIG_MONITORING_TOKEN }}
          sysdig-secure-url: https://us2.app.sysdig.com
